Repository OpenVoiceOS/ovos-skill-laugh, pull requests merged in 2024-11, with the labels that each got.

#36 chore: target correct version.py
  .github/workflows/publish_stable.yml
  .github/workflows/release_workflow.yml
  test/test_skill.py
Labels: ignore-for-release

#40 feat: royalty free images
  .github/workflows/update_skill_json.yml
  README.md
  skill.json
  sshot.png
  ui/images/0.jpg
  ui/images/1.jpg
  ui/images/2.jpg
  ui/images/3.jpg
Labels: feature

#43 fix: setup.py
  setup.py
Labels: fix
